// Centralized UI copy so a future i18n scaffold (constitution Principle VII)
// only has to wrap these values, not hunt them down across components.
export const strings = {
  appTitle: "OnlineMeter",
  navbar: {
    statusPage: "Status Page",
    dashboards: "Dashboards",
    settings: "Settings",
  },
  theme: {
    light: "Light",
    dark: "Dark",
    system: "System",
  },
  sidebar: {
    searchPlaceholder: "Search monitors…",
    ungrouped: "Ungrouped",
    noResults: "No monitors match your search.",
    addGroupPlaceholder: "New group name…",
    addGroup: "Add group",
    renameGroup: "Rename group",
    deleteGroup: "Delete group",
    deleteGroupConfirm: "Delete this group? Its monitors will move to Ungrouped, not be deleted.",
    deleteGroupTitle: "Delete group",
    deleteGroupAction: "Delete",
    deleteGroupCancel: "Cancel",
    makeGroupPublic: "Make public",
    makeGroupPrivate: "Make private",
    groupActions: "Group actions",
    renameDialogTitle: "Rename group",
    renameDialogLabel: "Name",
    renameDialogSave: "Save",
    renameDialogCancel: "Cancel",
  },
  dashboard: {
    title: "Overview",
    eyebrow: "Monitoring overview",
    empty: "No monitors yet. Add one to get started.",
    loading: "Loading monitor data…",
    addMonitor: "Add monitor",
    closeForm: "Close",
    disconnected: "Reconnecting…",
    stats: {
      total: "Total monitors",
      up: "Up",
      down: "Down",
      paused: "Paused",
      pending: "Pending",
    },
    statsContext: {
      total: "All configured monitors",
      up: "Currently responding",
      down: "Needs attention",
      paused: "Temporarily paused",
      pending: "Waiting for first check",
    },
    statsBadge: {
      total: "Live",
      up: "Healthy",
      down: "Attention",
      paused: "Paused",
      pending: "Pending",
    },
    trend: {
      title: "Uptime overview",
      subtitle: "Aggregated across all monitors",
      range7d: "Last 7 days",
      range30d: "Last 30 days",
    },
    table: {
      title: "Monitored targets",
      subtitle: "Current monitor inventory",
      name: "Name",
      type: "Type",
      target: "Target",
      status: "Status",
      uptimeRecent: "Uptime (recent)",
    },
  },
  monitorForm: {
    title: "New monitor",
    name: "Name",
    type: "Type",
    target: "Target",
    group: "Group",
    interval: "Interval (seconds)",
    timeout: "Timeout (seconds)",
    retries: "Retries",
    retryInterval: "Retry interval (seconds)",
    moreOptions: "More options",
    basicAuthHint: "For targets protected by HTTP Basic Authentication.",
    basicAuthUsername: "Username",
    basicAuthPassword: "Password",
    dnsRecordType: "Record type",
    dnsExpectedValue: "Expected value",
    dnsExpectedValueOptional: "Optional — any resolved value is accepted if left blank",
    keyword: "Keyword",
    keywordInvert: "Invert match (down when the keyword IS found)",
    submit: "Create monitor",
    submitting: "Creating…",
  },
  status: {
    pending: "Pending",
    up: "Up",
    down: "Down",
    paused: "Paused",
  },
  statusPage: {
    title: "Status",
    subtitle: "Current status of publicly shared monitors",
    empty: "No public status information is currently available.",
  },
  dashboards: {
    title: "Dashboards",
    subtitle: "Build focused views of your monitors, each with its own triggers",
    empty: "No dashboards yet. Create one to get started.",
    newDashboard: "New dashboard",
    createDialogTitle: "New dashboard",
    nameLabel: "Name",
    create: "Create",
    creating: "Creating…",
    rename: "Rename",
    renameDialogTitle: "Rename dashboard",
    renaming: "Saving…",
    delete: "Delete",
    deleteDialogTitle: "Delete dashboard",
    deleteConfirm:
      "Delete this dashboard? Its widgets will be removed. Monitors themselves are never affected.",
    deleteAction: "Delete",
    deleteCancel: "Cancel",
    addWidget: "Add widget",
    addWidgetDialogTitle: "Add widget",
    monitorLabel: "Monitor",
    triggerLabel: "Trigger",
    warningThresholdLabel: "Warning",
    criticalThresholdLabel: "Critical",
    removeWidget: "Remove",
    widgetEmpty: "No widgets yet. Add one to start watching a monitor here.",
    problem: "Critical",
    warning: "Warning",
    normal: "Normal",
    paused: "Paused",
    trigger: {
      status_down: "Status down",
      down_duration_minutes: "Down for longer than (minutes)",
      response_time_ms: "Response time above (ms)",
      certificate_expiry_days: "Certificate expires within (days)",
      docker_check_failing: "Docker check failing",
      uptime_below_percent: "Uptime (24h) below (%)",
    },
    triggerDescription: {
      status_down: "Flags this widget the moment the monitor reports it's down.",
      down_duration_minutes:
        "Flags this widget once the monitor has been continuously down for a while — useful to avoid alerting on brief blips.",
      response_time_ms:
        "Flags this widget when responses start taking too long, even if the monitor is technically still up.",
      certificate_expiry_days:
        "Flags this widget as its HTTPS certificate's expiry date approaches, so you can renew it in time.",
      docker_check_failing:
        "Flags this widget when the Docker container this monitor checks stops responding.",
      uptime_below_percent:
        "Flags this widget when its reliability over the last 24 hours drops below what you'd expect.",
    },
  },
  settings: {
    title: "Settings",
    subtitle: "Manage notification channels",
    channelsEmpty: "No notification channels yet. Add one below.",
    addChannelTitle: "Add channel",
    channelName: "Name",
    channelUrl: "Webhook URL",
    addChannel: "Add channel",
    adding: "Adding…",
    test: "Send test",
    testing: "Sending…",
    enable: "Enable",
    disable: "Disable",
    delete: "Delete",
    deleteChannelTitle: "Delete channel",
    deleteChannelConfirm: "Delete this notification channel? This cannot be undone.",
    deleteChannelAction: "Delete",
    deleteChannelCancel: "Cancel",
    deliveryNever: "No delivery yet",
    deliverySucceeded: "Last delivery succeeded",
    deliveryFailed: "Last delivery failed",
  },
  detail: {
    stats: {
      current: "Response (current)",
      avg24h: "Avg. response (24h)",
      uptime24h: "Uptime (24h)",
      uptime30d: "Uptime (30d)",
    },
    history: "Response time",
    log: "Event log",
    empty: "No checks recorded yet.",
    certificateExpires: "Certificate expires",
    certificateExpiringSoon: "Expiring soon",
    pause: "Pause",
    resume: "Resume",
    delete: "Delete",
    deleteConfirm:
      "Delete this monitor? Its check history will be deleted too. This cannot be undone.",
    edit: "Edit",
    save: "Save",
    saving: "Saving…",
    cancel: "Cancel",
    logViewFull: "Full",
    logViewCondensed: "Condensed",
    logStreakSummary: (count: number) => `× ${count} checks`,
    logRangeLabel: "Period",
    logRangeLast24h: "Last 24 hours",
    logRangeLast7d: "Last 7 days",
    logRangeLast30d: "Last 30 days",
    logRangeCustom: "Custom range…",
    logRangeFrom: "From",
    logRangeTo: "To",
    logRangeApply: "Apply",
    logRangeErrorOrder: "The end must not be before the start.",
    logRangeErrorFuture: "This period is entirely in the future.",
    logRangeErrorIncomplete: "Select a start and end date.",
  },
} as const;
