// Centralized UI copy so a future i18n scaffold (constitution Principle VII)
// only has to wrap these values, not hunt them down across components.
export const strings = {
  appTitle: "OnlineMeter",
  navbar: {
    statusPage: "Status Page",
    settings: "Settings",
  },
  theme: {
    light: "Light",
    dark: "Dark",
    system: "System",
  },
  sidebar: {
    searchPlaceholder: "Search monitors…",
    ungrouped: "Ungrouped",
    noResults: "No monitors match your search.",
    addGroupPlaceholder: "New group name…",
    addGroup: "Add group",
    renameGroup: "Rename group",
    deleteGroup: "Delete group",
    deleteGroupConfirm: "Delete this group? Its monitors will move to Ungrouped, not be deleted.",
    deleteGroupTitle: "Delete group",
    deleteGroupAction: "Delete",
    deleteGroupCancel: "Cancel",
    makeGroupPublic: "Make public",
    makeGroupPrivate: "Make private",
    groupActions: "Group actions",
    renameDialogTitle: "Rename group",
    renameDialogLabel: "Name",
    renameDialogSave: "Save",
    renameDialogCancel: "Cancel",
  },
  dashboard: {
    title: "Overview",
    eyebrow: "Monitoring overview",
    empty: "No monitors yet. Add one to get started.",
    loading: "Loading monitor data…",
    addMonitor: "Add monitor",
    closeForm: "Close",
    disconnected: "Reconnecting…",
    stats: {
      total: "Total monitors",
      up: "Up",
      down: "Down",
      paused: "Paused",
      pending: "Pending",
    },
    statsContext: {
      total: "All configured monitors",
      up: "Currently responding",
      down: "Needs attention",
      paused: "Temporarily paused",
      pending: "Waiting for first check",
    },
    statsBadge: {
      total: "Live",
      up: "Healthy",
      down: "Attention",
      paused: "Paused",
      pending: "Pending",
    },
    trend: {
      title: "Uptime overview",
      subtitle: "Aggregated across all monitors",
      range7d: "Last 7 days",
      range30d: "Last 30 days",
    },
    table: {
      title: "Monitored targets",
      subtitle: "Current monitor inventory",
      name: "Name",
      type: "Type",
      target: "Target",
      status: "Status",
      uptimeRecent: "Uptime (recent)",
    },
  },
  monitorForm: {
    title: "New monitor",
    name: "Name",
    type: "Type",
    target: "Target",
    group: "Group",
    interval: "Interval (seconds)",
    timeout: "Timeout (seconds)",
    moreOptions: "More options",
    basicAuthHint: "For targets protected by HTTP Basic Authentication.",
    basicAuthUsername: "Username",
    basicAuthPassword: "Password",
    dnsRecordType: "Record type",
    dnsExpectedValue: "Expected value",
    dnsExpectedValueOptional: "Optional — any resolved value is accepted if left blank",
    keyword: "Keyword",
    keywordInvert: "Invert match (down when the keyword IS found)",
    submit: "Create monitor",
    submitting: "Creating…",
  },
  status: {
    pending: "Pending",
    up: "Up",
    down: "Down",
    paused: "Paused",
  },
  statusPage: {
    title: "Status",
    subtitle: "Current status of publicly shared monitors",
    empty: "No public status information is currently available.",
  },
  settings: {
    title: "Settings",
    subtitle: "Manage notification channels",
    channelsEmpty: "No notification channels yet. Add one below.",
    addChannelTitle: "Add channel",
    channelName: "Name",
    channelUrl: "Webhook URL",
    addChannel: "Add channel",
    adding: "Adding…",
    test: "Send test",
    testing: "Sending…",
    enable: "Enable",
    disable: "Disable",
    delete: "Delete",
    deleteChannelTitle: "Delete channel",
    deleteChannelConfirm: "Delete this notification channel? This cannot be undone.",
    deleteChannelAction: "Delete",
    deleteChannelCancel: "Cancel",
    deliveryNever: "No delivery yet",
    deliverySucceeded: "Last delivery succeeded",
    deliveryFailed: "Last delivery failed",
  },
  demo: {
    bannerTitle: "Demo",
    bannerBody: "This is a public read-only demo — changes are disabled.",
    disabledTitle: "Disabled in demo mode",
  },
  detail: {
    stats: {
      current: "Response (current)",
      avg24h: "Avg. response (24h)",
      uptime24h: "Uptime (24h)",
      uptime30d: "Uptime (30d)",
    },
    history: "Response time",
    log: "Event log",
    empty: "No checks recorded yet.",
    certificateExpires: "Certificate expires",
    certificateExpiringSoon: "Expiring soon",
    pause: "Pause",
    resume: "Resume",
    delete: "Delete",
    deleteConfirm:
      "Delete this monitor? Its check history will be deleted too. This cannot be undone.",
    edit: "Edit",
    save: "Save",
    saving: "Saving…",
    cancel: "Cancel",
  },
} as const;
